name: release scriptengine
on:
  workflow_dispatch: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21
          cache: gradle

      - name: Publish package
        run: ./gradlew clean :scriptengine:publish
        env:
          GITHUB_TOKEN: ${{ secrets.ASKOURA_PAT }}
